//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class bgDBContainer : DbContext
    {
        public bgDBContainer()
            : base("name=bgDBContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Country> Country { get; set; }
        public virtual DbSet<LogType> LogType { get; set; }
        public virtual DbSet<EmailType> EmailType { get; set; }
        public virtual DbSet<AddressType> AddressType { get; set; }
        public virtual DbSet<PhoneType> PhoneType { get; set; }
        public virtual DbSet<Person> Person { get; set; }
        public virtual DbSet<Member> Member { get; set; }
        public virtual DbSet<Salutation> Salutation { get; set; }
        public virtual DbSet<Occupation> Occupation { get; set; }
        public virtual DbSet<JobTitle> JobTitle { get; set; }
        public virtual DbSet<TransactionType> TransactionType { get; set; }
        public virtual DbSet<UploadType> UploadType { get; set; }
        public virtual DbSet<PersonUpload> PersonUpload { get; set; }
        public virtual DbSet<SocialProfileType> SocialProfileType { get; set; }
        public virtual DbSet<PersonSocialProfile> PersonSocialProfile { get; set; }
        public virtual DbSet<PersonPhone> PersonPhone { get; set; }
        public virtual DbSet<PersonEmail> PersonEmail { get; set; }
        public virtual DbSet<PersonAddress> PersonAddress { get; set; }
        public virtual DbSet<PersonOccupation> PersonOccupation { get; set; }
        public virtual DbSet<Log> Log { get; set; }
        public virtual DbSet<Transaction> Transaction { get; set; }
        public virtual DbSet<Login> Login { get; set; }
        public virtual DbSet<PersonTypeRole> PersonRole { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<PersonType> PersonType { get; set; }
        public virtual DbSet<MailoutQueue> MailoutQueue { get; set; }
        public virtual DbSet<MailoutType> MailoutType { get; set; }
        public virtual DbSet<MailoutParameter> MailoutParameter { get; set; }
        public virtual DbSet<MailoutTypeParameter> MailoutTypeParameter { get; set; }
        public virtual DbSet<MailoutQueueParameterValue> MailoutQueueParameterValue { get; set; }
        public virtual DbSet<MailoutTracker> MailoutTracker { get; set; }
        public virtual DbSet<Attendance> Attendance { get; set; }
        public virtual DbSet<SecurityType> SecurityType { get; set; }
        public virtual DbSet<SecurityCode> SecurityCode { get; set; }
    }
}
