ALTER TABLE BG.AddressType ADD UNIQUE (Name)
ALTER TABLE BG.EmailType ADD UNIQUE (Name)
ALTER TABLE BG.JobTitle ADD UNIQUE (Name)
ALTER TABLE BG.LogType ADD UNIQUE (Name)
ALTER TABLE BG.Occupation ADD UNIQUE (Name)
ALTER TABLE BG.PhoneType ADD UNIQUE (Name)
ALTER TABLE BG.Salutation ADD UNIQUE (Name)
ALTER TABLE BG.SocialProfileType ADD UNIQUE (Name)
ALTER TABLE BG.TransactionType ADD UNIQUE (Code)
ALTER TABLE BG.UploadType ADD UNIQUE (Name)


ALTER TABLE BG.PersonEmail ADD UNIQUE (Value)
ALTER TABLE BG.PersonEmail ADD CONSTRAINT UNQKEY_PERSONEMAILTYPE UNIQUE(EmailTypeId,PersonId)
ALTER TABLE BG.PersonAddress ADD CONSTRAINT UNQKEY_PERSONADDRESSTYPE UNIQUE(AddressTypeId,PersonId)
ALTER TABLE BG.PersonPhone ADD CONSTRAINT UNQKEY_PERSONPHONETYPE UNIQUE(PhoneTypeId,PersonId)


ALTER TABLE BG.Login ADD UNIQUE (Username)
ALTER TABLE BG.PersonType ADD UNIQUE (Name)
ALTER TABLE BG.MailoutType ADD UNIQUE (Name)
ALTER TABLE BG.MailoutTypeParameter ADD CONSTRAINT UNQKEY_MailoutTypeParameter UNIQUE(MailoutTypeId,MailoutParameterId)
ALTER TABLE BG.MailoutParameter ADD UNIQUE (Name)

ALTER TABLE BG.Attendance ADD CONSTRAINT UNQKEY_PERSONDATE UNIQUE(PersonId,AttendanceDate)

ALTER TABLE BG.[Transaction] ADD CONSTRAINT UNQKEY_PERSON_TRANSACTION UNIQUE(PersonId,TransactionTypeId,CreatedOn)

