insert into bg.country values('AF','Afghanistan',1)
insert into bg.country values('AX','Aland Islands',1)
insert into bg.country values('AL','Albania',1)
insert into bg.country values('DZ','Algeria',1)
insert into bg.country values('AS','American Samoa',1)
insert into bg.country values('AD','Andorra',1)
insert into bg.country values('AO','Angola',1)
insert into bg.country values('AI','Anguilla',1)
insert into bg.country values('AQ','Antarctica',1)
insert into bg.country values('AG','Antigua and Barbuda',1)
insert into bg.country values('AR','Argentina',1)
insert into bg.country values('AM','Armenia',1)
insert into bg.country values('AW','Aruba',1)
insert into bg.country values('AC','Ascension Island',1)
insert into bg.country values('AP','Asia Pacific',1)
insert into bg.country values('AU','Australia',1)
insert into bg.country values('AT','Austria',1)
insert into bg.country values('AZ','Azerbaijan',1)
insert into bg.country values('BS','Bahamas',1)
insert into bg.country values('BH','Bahrain',1)
insert into bg.country values('BD','Bangladesh',1)
insert into bg.country values('BB','Barbados',1)
insert into bg.country values('BY','Belarus',1)
insert into bg.country values('BE','Belgium',1)
insert into bg.country values('BZ','Belize',1)
insert into bg.country values('BJ','Benin',1)
insert into bg.country values('BM','Bermuda',1)
insert into bg.country values('BT','Bhutan',1)
insert into bg.country values('BO','Bolivia',1)
insert into bg.country values('BA','Bosnia and Herzegovina',1)
insert into bg.country values('BW','Botswana',1)
insert into bg.country values('BV','Bouvet Island',1)
insert into bg.country values('BR','Brazil',1)
insert into bg.country values('IO','British Indian Ocean Territory',1)
insert into bg.country values('BN','Brunei Darussalam',1)
insert into bg.country values('BG','Bulgaria',1)
insert into bg.country values('BF','Burkina Faso',1)
insert into bg.country values('BI','Burundi',1)
insert into bg.country values('KH','Cambodia',1)
insert into bg.country values('CM','Cameroon',1)
insert into bg.country values('CA','Canada',1)
insert into bg.country values('CV','Cape Verde',1)
insert into bg.country values('KY','Cayman Islands',1)
insert into bg.country values('CF','Central African Republic',1)
insert into bg.country values('TD','Chad',1)
insert into bg.country values('CL','Chile',1)
insert into bg.country values('CN','China',1)
insert into bg.country values('CX','Christmas Island',1)
insert into bg.country values('CC','Cocos (Keeling) Islands',1)
insert into bg.country values('CO','Colombia',1)
insert into bg.country values('KM','Comoros',1)
insert into bg.country values('CG','Congo, Republic of',1)
insert into bg.country values('CD','Congo, The Democratic Republic of the',1)
insert into bg.country values('CK','Cook Islands',1)
insert into bg.country values('CR','Costa Rica',1)
insert into bg.country values('CI','Cote d''Ivoire',1)
insert into bg.country values('HR','Croatia',1)
insert into bg.country values('CU','Cuba',1)
insert into bg.country values('CY','Cyprus',1)
insert into bg.country values('CZ','Czech Republic',1)
insert into bg.country values('DK','Denmark',1)
insert into bg.country values('DJ','Djibouti',1)
insert into bg.country values('DM','Dominica',1)
insert into bg.country values('DO','Dominican Republic',1)
insert into bg.country values('EC','Ecuador',1)
insert into bg.country values('EG','Egypt',1)
insert into bg.country values('SV','El Salvador',1)
insert into bg.country values('GQ','Equatorial Guinea',1)
insert into bg.country values('ER','Eritrea',1)
insert into bg.country values('EE','Estonia',1)
insert into bg.country values('ET','Ethiopia',1)
insert into bg.country values('EU','European Union',1)
insert into bg.country values('FK','Falkland Islands (Malvinas)',1)
insert into bg.country values('FO','Faroe Islands',1)
insert into bg.country values('FJ','Fiji',1)
insert into bg.country values('FI','Finland',1)
insert into bg.country values('FR','France',1)
insert into bg.country values('GF','French Guiana',1)
insert into bg.country values('PF','French Polynesia',1)
insert into bg.country values('TF','French Southern Territories',1)
insert into bg.country values('GA','Gabon',1)
insert into bg.country values('GM','Gambia',1)
insert into bg.country values('GE','Georgia',1)
insert into bg.country values('DE','Germany',1)
insert into bg.country values('GH','Ghana',1)
insert into bg.country values('GI','Gibraltar',1)
insert into bg.country values('GR','Greece',1)
insert into bg.country values('GL','Greenland',1)
insert into bg.country values('GD','Grenada',1)
insert into bg.country values('GP','Guadeloupe',1)
insert into bg.country values('GU','Guam',1)
insert into bg.country values('GT','Guatemala',1)
insert into bg.country values('GG','Guernsey',1)
insert into bg.country values('GN','Guinea',1)
insert into bg.country values('GW','Guinea-Bissau',1)
insert into bg.country values('GY','Guyana',1)
insert into bg.country values('HT','Haiti',1)
insert into bg.country values('HM','Heard and McDonald Islands',1)
insert into bg.country values('VA','Holy See (Vatican City State)',1)
insert into bg.country values('HN','Honduras',1)
insert into bg.country values('HK','Hong Kong',1)
insert into bg.country values('HU','Hungary',1)
insert into bg.country values('IS','Iceland',1)
insert into bg.country values('IN','India',1)
insert into bg.country values('ID','Indonesia',1)
insert into bg.country values('IR','Iran, Islamic Republic of',1)
insert into bg.country values('IQ','Iraq',1)
insert into bg.country values('IE','Ireland',1)
insert into bg.country values('IM','Isle of Man',1)
insert into bg.country values('IL','Israel',1)
insert into bg.country values('IT','Italy',1)
insert into bg.country values('JM','Jamaica',1)
insert into bg.country values('JP','Japan',1)
insert into bg.country values('JE','Jersey',1)
insert into bg.country values('JO','Jordan',1)
insert into bg.country values('KZ','Kazakhstan',1)
insert into bg.country values('KE','Kenya',1)
insert into bg.country values('KI','Kiribati',1)
insert into bg.country values('KP','Korea, Democratic People''s Republic',1)
insert into bg.country values('KR','Korea, Republic of',1)
insert into bg.country values('KW','Kuwait',1)
insert into bg.country values('KG','Kyrgyzstan',1)
insert into bg.country values('LA','Lao People''s Democratic Republic',1)
insert into bg.country values('LV','Latvia',1)
insert into bg.country values('LB','Lebanon',1)
insert into bg.country values('LS','Lesotho',1)
insert into bg.country values('LR','Liberia',1)
insert into bg.country values('LY','Libyan Arab Jamahiriya',1)
insert into bg.country values('LI','Liechtenstein',1)
insert into bg.country values('LT','Lithuania',1)
insert into bg.country values('LU','Luxembourg',1)
insert into bg.country values('MO','Macau',1)
insert into bg.country values('MK','Macedonia, The Former Yugoslav Republic of',1)
insert into bg.country values('MG','Madagascar',1)
insert into bg.country values('MW','Malawi',1)
insert into bg.country values('MY','Malaysia',1)
insert into bg.country values('MV','Maldives',1)
insert into bg.country values('ML','Mali',1)
insert into bg.country values('MT','Malta',1)
insert into bg.country values('MH','Marshall Islands',1)
insert into bg.country values('MQ','Martinique',1)
insert into bg.country values('MR','Mauritania',1)
insert into bg.country values('MU','Mauritius',1)
insert into bg.country values('YT','Mayotte',1)
insert into bg.country values('MX','Mexico',1)
insert into bg.country values('FM','Micronesia, Federal State of',1)
insert into bg.country values('MD','Moldova, Republic of',1)
insert into bg.country values('MC','Monaco',1)
insert into bg.country values('MN','Mongolia',1)
insert into bg.country values('ME','Montenegro',1)
insert into bg.country values('MS','Montserrat',1)
insert into bg.country values('MA','Morocco',1)
insert into bg.country values('MZ','Mozambique',1)
insert into bg.country values('MM','Myanmar',1)
insert into bg.country values('NA','Namibia',1)
insert into bg.country values('NR','Nauru',1)
insert into bg.country values('NP','Nepal',1)
insert into bg.country values('NL','Netherlands',1)
insert into bg.country values('AN','Netherlands Antilles',1)
insert into bg.country values('NC','New Caledonia',1)
insert into bg.country values('NZ','New Zealand',1)
insert into bg.country values('NI','Nicaragua',1)
insert into bg.country values('NE','Niger',1)
insert into bg.country values('NG','Nigeria',1)
insert into bg.country values('NU','Niue',1)
insert into bg.country values('NF','Norfolk Island',1)
insert into bg.country values('MP','Northern Mariana Islands',1)
insert into bg.country values('NO','Norway',1)
insert into bg.country values('OM','Oman',1)
insert into bg.country values('XX','Other',1)
insert into bg.country values('PK','Pakistan',1)
insert into bg.country values('PW','Palau',1)
insert into bg.country values('PS','Palestinian Territories',1)
insert into bg.country values('PA','Panama',1)
insert into bg.country values('PG','Papua New Guinea',1)
insert into bg.country values('PY','Paraguay',1)
insert into bg.country values('PE','Peru',1)
insert into bg.country values('PH','Philippines',1)
insert into bg.country values('PN','Pitcairn Island',1)
insert into bg.country values('PL','Poland',1)
insert into bg.country values('PT','Portugal',1)
insert into bg.country values('PR','Puerto Rico',1)
insert into bg.country values('QA','Qatar',1)
insert into bg.country values('RE','Reunion Island',1)
insert into bg.country values('RO','Romania',1)
insert into bg.country values('RU','Russian Federation',1)
insert into bg.country values('RW','Rwanda',1)
insert into bg.country values('SH','Saint Helena',1)
insert into bg.country values('KN','Saint Kitts and Nevis',1)
insert into bg.country values('LC','Saint Lucia',1)
insert into bg.country values('PM','Saint Pierre and Miquelon',1)
insert into bg.country values('VC','Saint Vincent and the Grenadines',1)
insert into bg.country values('SM','San Marino',1)
insert into bg.country values('ST','Sao Tome and Principe',1)
insert into bg.country values('SA','Saudi Arabia',1)
insert into bg.country values('SN','Senegal',1)
insert into bg.country values('RS','Serbia',1)
insert into bg.country values('CS','Serbia and Montenegro',1)
insert into bg.country values('SC','Seychelles',1)
insert into bg.country values('SL','Sierra Leone',1)
insert into bg.country values('SG','Singapore',1)
insert into bg.country values('SK','Slovak Republic',1)
insert into bg.country values('SI','Slovenia',1)
insert into bg.country values('SB','Solomon Islands',1)
insert into bg.country values('SO','Somalia',1)
insert into bg.country values('ZA','South Africa',1)
insert into bg.country values('GS','South Georgia and the South Sandwich Islands',1)
insert into bg.country values('ES','Spain',1)
insert into bg.country values('LK','Sri Lanka',1)
insert into bg.country values('SD','Sudan',1)
insert into bg.country values('SR','Suriname',1)
insert into bg.country values('SJ','Svalbard and Jan Mayen Islands',1)
insert into bg.country values('SZ','Swaziland',1)
insert into bg.country values('SE','Sweden',1)
insert into bg.country values('CH','Switzerland',1)
insert into bg.country values('SY','Syrian Arab Republic',1)
insert into bg.country values('TW','Taiwan',1)
insert into bg.country values('TJ','Tajikistan',1)
insert into bg.country values('TZ','Tanzania',1)
insert into bg.country values('TH','Thailand',1)
insert into bg.country values('TL','Timor-Leste',1)
insert into bg.country values('TG','Togo',1)
insert into bg.country values('TK','Tokelau',1)
insert into bg.country values('TO','Tonga',1)
insert into bg.country values('TT','Trinidad and Tobago',1)
insert into bg.country values('TN','Tunisia',1)
insert into bg.country values('TR','Turkey',1)
insert into bg.country values('TM','Turkmenistan',1)
insert into bg.country values('TC','Turks and Caicos Islands',1)
insert into bg.country values('TV','Tuvalu',1)
insert into bg.country values('UG','Uganda',1)
insert into bg.country values('UA','Ukraine',1)
insert into bg.country values('AE','United Arab Emirates',1)
insert into bg.country values('UK','United Kingdom',1)
insert into bg.country values('UM','United States Minor Outlying Islands',1)
insert into bg.country values('US','United States Of America',1)
insert into bg.country values('UY','Uruguay',1)
insert into bg.country values('UZ','Uzbekistan',1)
insert into bg.country values('VU','Vanuatu',1)
insert into bg.country values('VE','Venezuela',1)
insert into bg.country values('VN','Vietnam',1)
insert into bg.country values('VG','Virgin Islands, British',1)
insert into bg.country values('VI','Virgin Islands, U.S.',1)
insert into bg.country values('WF','Wallis and Futuna Islands',1)
insert into bg.country values('EH','Western Sahara',1)
insert into bg.country values('WS','Western Samoa',1)
insert into bg.country values('YE','Yemen',1)
insert into bg.country values('YU','Yugoslavia',1)
insert into bg.country values('ZM','Zambia',1)
insert into bg.country values('ZW','Zimbabwe',1)



insert into BG.AddressType values('HOME')
insert into BG.AddressType values('WORK')

insert into BG.EmailType values('PERSONAL')
insert into BG.EmailType values('OFFICIAL')

insert into BG.LogType values('EXCEPTION')
insert into BG.LogType values('TRACKING')
insert into BG.LogType values('EMAILEXCEPTION')


insert into BG.PhoneType values('MOBILE')
insert into BG.PhoneType values('HOME LANDLINE')
insert into BG.PhoneType values('OFFICE LANDLINE')

insert into BG.Salutation values('Mr')
insert into BG.Salutation values('Mrs')
insert into BG.Salutation values('Miss')
insert into BG.Salutation values('Dr')
insert into BG.Salutation values('Ms')

insert into BG.SocialProfileType values('FACEBOOK')
insert into BG.SocialProfileType values('LINKEDIN')
insert into BG.SocialProfileType values('GOOGLEPLUS')
insert into BG.SocialProfileType values('TWITTER')

insert into BG.TransactionType values('DEP','FUND DEPOSIT',1.0000)
insert into BG.TransactionType values('CBK','PARTICIPATION FEE',-1.0000)
insert into BG.TransactionType values('CMN','COMMON ACCOUNT EXPENSE',-1.0000)
insert into BG.TransactionType values('CCM','CONDITIONAL COMMON ACCOUNT EXPENSE',-1.0000)

insert into BG.UploadType values('PROFILE PICTURE')

insert into BG.Role values('SYSADMIN','SYSTEMADMIN',GETDATE())
insert into BG.Role values('PLAYER','PLAYER',GETDATE())

insert into BG.PersonType values('SYSADMIN')
insert into BG.PersonType values('PLAYER')

insert into BG.securitytype values('JOINING')
insert into BG.securitytype values('FORGOTPASSWORD')


insert into BG.MailoutType values ('tmpJoin','On member joining',1,GETDATE(),'Welcome Aboard')
insert into BG.MailoutType values ('tmpCredential','On online account setup',1,GETDATE(),'Your Login Details')

insert into BG.MailoutType values ('tmpForgotPassword','On password reset request',1,GETDATE(),'Forgotten Your Password?')
insert into BG.MailoutType values ('tmpPasswordAck','After a new password has been generated',1,GETDATE(),'Your New Password')

insert into BG.MailoutType values ('tmpSupport','After a new suppory query has been raised',1,GETDATE(),'New Ticket')

insert into BG.MailoutType values ('tmpDefault','When admin sends a message',1,GETDATE(),'Message from Admin')

insert into BG.MailoutType values ('tmpAccountBalance','On Member account balance notification',1,GETDATE(),'Your account balance')



insert into BG.MailoutParameter values('Name','Name')
insert into BG.MailoutParameter values('Message','Message Content')
insert into BG.MailoutParameter values('VerificationLink','Verification Link')
insert into BG.MailoutParameter values('ResetLink','Reset Link')
insert into BG.MailoutParameter values('SecurityCode','Security Code')
insert into BG.MailoutParameter values('Username','Username')
insert into BG.MailoutParameter values('Password','Password')
insert into BG.MailoutParameter values('Emailaddress','Emailaddress')
insert into BG.MailoutParameter values('Balance','Account Balance')





/*ON JOINING */
insert into BG.MailoutTypeParameter values(1,1,1)
insert into BG.MailoutTypeParameter values(1,1,3)

/*ON VERIFICATION*/
insert into BG.MailoutTypeParameter values(1,2,1)


/*ON PASSWORD RESET REQUEST*/
insert into BG.MailoutTypeParameter values(1,3,1)
insert into BG.MailoutTypeParameter values(1,3,4)
insert into BG.MailoutTypeParameter values(1,3,5)

/*ON LOGIN SETUP*/

insert into BG.MailoutTypeParameter values(1,2,6)
insert into BG.MailoutTypeParameter values(1,2,7)

/*ON NEW SUPPORT QUERY*/

insert into BG.MailoutTypeParameter values(1,5,1)
insert into BG.MailoutTypeParameter values(1,5,2)
insert into BG.MailoutTypeParameter values(1,5,8)

/*WHEN ADMIN SENDS MESSAGE*/
insert into BG.MailoutTypeParameter values(1,6,1)
insert into BG.MailoutTypeParameter values(1,6,2)

/*WHEN SYSTEM SENDS BALANCE NOTIFICATION*/
insert into BG.MailoutTypeParameter values(1,7,9)
insert into BG.MailoutTypeParameter values(1,7,1)


/*New Template: 21 Feb 2020*/
insert into BG.MailoutType values ('tmpAttendance','On Member attendance captured notification',1,GETDATE(),'Thanks once again buddy..')

insert into BG.MailoutParameter values('Amount','Amount')
insert into BG.MailoutParameter values('Units','Hour Units')

insert into BG.MailoutTypeParameter values(1,8,1)
insert into BG.MailoutTypeParameter values(1,8,10)
insert into BG.MailoutTypeParameter values(1,8,11)

  insert into BG.MailoutType values ('tmpPayment','On Member payment received notification',1,GETDATE(),'Your recent transaction')

insert into BG.MailoutTypeParameter values(1,9,1)
insert into BG.MailoutTypeParameter values(1,9,2)