//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonPhone
    {
        public int Id { get; set; }
        public int PhoneTypeId { get; set; }
        public int PersonId { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string Value { get; set; }
    
        public virtual PhoneType PhoneType { get; set; }
        public virtual Person Person { get; set; }
    }
}
