//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public int Id { get; set; }
        public int TransactionTypeId { get; set; }
        public int PersonId { get; set; }
        public decimal Amount { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string Remarks { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual TransactionType TransactionType { get; set; }
        public virtual Person Person { get; set; }
    }
}
